[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
arx_predict = "5Db7RmGdiKLf1G3CQjxmzoS86YBRhAxVZJYrWXDzDVde"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/arx_predict.ts"
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/arx_predict_multiple.ts"

address = "BKck65TgoKRokMjQM3datB9oRwJ8rAj2jxPXvHXUvcL6"
program = "/home/jovian/projects/arcium/arx_predict/artifacts/arcium_program_0.2.0.so"
